# Generated by Django 5.2.6 on 2025-11-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visibility',
        ),
    ]
