# Generated by Django 5.2.6 on 2025-11-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visibility',
        ),
    ]
