# Generated by Django 5.2.6 on 2025-11-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='pfp',
        ),
    ]
